service: example

frameworkVersion: "2"
configValidationMode: error
useDotenv: true
variablesResolutionMode: "20210326"
unresolvedVariablesNotificationMode: error
disabledDeprecations: []

custom:
  warmup:
    default:
      enable: true
      prewarm: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup

functions:
  hello:
    handler: routes/hello.handler
    events:
      - http:
          path: /hello
          method: GET
