version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14-bullseye
    init: true
    hostname: app
    volumes:
      - ..:/workspace:cached
      - $HOME/.aws/credentials:/home/node/.aws/credentials:ro
      - $HOME/.aws/config:/home/node/.aws/config:ro
    command: sleep infinity
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /var/lib/dynamodb/data/
    restart: unless-stopped
    network_mode: service:app
    user: root
    volumes:
      - data:/var/lib/dynamodb/data
  dynamodb-viewer:
    image: taydy/dynamodb-manager
    network_mode: service:app
volumes:
  data: {}
